# Generated by Django 4.0.4 on 2022-04-22 06:59

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_alter_lesson_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('student_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('qualification_level', models.CharField(choices=[('1', 'Undergraduate'), ('2', 'Graduate'), ('3', 'Continuing education')], max_length=50)),
                ('email', users.models.CIEmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('R', 'Rather not say')], max_length=150)),
                ('address', models.CharField(max_length=400)),
                ('state', models.CharField(choices=[('1', 'Andhra Pradesh'), ('2', 'Arunachal Pradesh'), ('3', 'Assam'), ('4', 'Bihar'), ('5', 'Chhattisgarh'), ('6', 'Goa'), ('7', 'Gujarat'), ('8', 'Haryana'), ('9', 'Himachal Pradesh'), ('10', 'Jharkhand'), ('11', 'Karnataka'), ('12', 'Kerala'), ('13', 'Madhya Pradesh'), ('14', 'Maharashtra'), ('15', 'Manipur'), ('16', 'Meghalaya'), ('17', 'Mizoram'), ('18', 'Nagaland'), ('19', 'Odisha'), ('20', 'Punjab'), ('21', 'Rajasthan'), ('22', 'Sikkim'), ('23', 'Tamil Nadu'), ('24', 'Telangana'), ('25', 'Tripura'), ('26', 'Uttar Pradesh'), ('27', 'Uttarakhand'), ('28', 'West Bengal')], max_length=200)),
                ('admission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
    ]
