# Generated by Django 4.0.4 on 2022-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('0', 'PENDING'), ('1', 'COMPLETED')], default='0', max_length=15),
        ),
    ]
