# Generated by Django 4.0.4 on 2022-04-22 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.ImageField(upload_to='')),
                ('highschool_diploma', models.FileField(upload_to='')),
                ('graduate_degree', models.FileField(blank=True, null=True, upload_to='')),
                ('address_proof', models.FileField(upload_to='')),
                ('undertaking', models.FileField(upload_to='')),
                ('verified', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
            ],
        ),
    ]
