# Generated by Django 4.0.4 on 2022-04-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_alter_document_graduate_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='graduate_degree',
        ),
    ]
