# Generated by Django 4.0.4 on 2022-04-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('duration', models.PositiveIntegerField(default=4)),
                ('description', models.TextField()),
                ('stream', models.CharField(choices=[('1', 'Science'), ('2', 'Arts'), ('3', 'Sports'), ('4', 'Others')], max_length=55)),
                ('hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
