# Generated by Django 4.0.4 on 2022-04-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_name_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('1', 'Theory'), ('2', 'Practical')], max_length=50),
        ),
    ]
