# Generated by Django 4.0.4 on 2022-04-20 04:42

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.models.CIEmailField(max_length=30, unique=True),
        ),
    ]
