# Generated by Django 4.0.4 on 2022-04-24 05:00

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.models.CIEmailField(max_length=150, unique=True),
        ),
    ]
