# Generated by Django 4.0.4 on 2022-04-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='graduate_degree',
        ),
    ]
